### ISSUE TITLE
i don't believe this is an issue with the code, but i am going to ask anyway

### ISSUE THREAD

**Issue by ambraglow** [asig/ps2-to-xt-adapter#2]
so i flashed the code for an attiny85, but i have no input on my ibm and still a 301 error i have no clue what is wrong at this point.
i am using digispark 5160 (micronucleus bootloader)
ibm 5160
my ps2 keyboard is a dell quietkey

**Comment by asig** [comment]
Are you sure that the code is actually flashed, and that your keyboard is actually working?

You can also compile the code for a more powerful controller (e.g. ATmega328). Just comment out the "#define ATTINY85" on line 26. This will enable debug mode that dumps the "traffic" to the serial interface, so you can watch from the IDE's serial monitor. Note that the pin assignment is different when compiled for non-attiny85.

Alternatively, you can also hook up a logic analyzer to the input and output pins, and see what signals you get. Any cheap analyzer from Aliexpress will do.

Hope that helps!
